
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;

	private global::Gtk.Label outputLabel;

	private global::Gtk.Table table1;

	private global::Gtk.Button Btn;

	private global::Gtk.Button Btn1;

	private global::Gtk.Button Btn2;

	private global::Gtk.Button Btn3;

	private global::Gtk.Button Btn4;

	private global::Gtk.Button Btn5;

	private global::Gtk.Button Btn6;

	private global::Gtk.Button Btn7;

	private global::Gtk.Button Btn8;

	private global::Gtk.Button Btn9;

	private global::Gtk.Button BtnClear;

	private global::Gtk.Button BtnDecimalPt;

	private global::Gtk.Button BtnDel;

	private global::Gtk.Button BtnDivide1;

	private global::Gtk.Button BtnEquals;

	private global::Gtk.Button BtnMinus;

	private global::Gtk.Button BtnMultiply;

	private global::Gtk.Button BtnPlus;

	private global::Gtk.Button BtnPlusMinus;

	private global::Gtk.Button BtnPwr;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Dead Simple Calculator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		this.vbox3.BorderWidth = ((uint)(5));
		// Container child vbox3.Gtk.Box+BoxChild
		this.outputLabel = new global::Gtk.Label();
		this.outputLabel.Name = "outputLabel";
		this.outputLabel.Xpad = 10;
		this.outputLabel.Xalign = 1F;
		this.outputLabel.LabelProp = global::Mono.Unix.Catalog.GetString("0");
		this.outputLabel.Justify = ((global::Gtk.Justification)(1));
		this.vbox3.Add(this.outputLabel);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.outputLabel]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		w1.Padding = ((uint)(32));
		// Container child vbox3.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(5)), ((uint)(4)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(9));
		// Container child table1.Gtk.Table+TableChild
		this.Btn = new global::Gtk.Button();
		this.Btn.Name = "Btn";
		this.Btn.UseUnderline = true;
		this.Btn.Label = global::Mono.Unix.Catalog.GetString("0");
		this.table1.Add(this.Btn);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.Btn]));
		w2.TopAttach = ((uint)(4));
		w2.BottomAttach = ((uint)(5));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.Btn1 = new global::Gtk.Button();
		this.Btn1.Name = "Btn1";
		this.Btn1.UseUnderline = true;
		this.Btn1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.table1.Add(this.Btn1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.Btn1]));
		w3.TopAttach = ((uint)(3));
		w3.BottomAttach = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.Btn2 = new global::Gtk.Button();
		this.Btn2.Name = "Btn2";
		this.Btn2.UseUnderline = true;
		this.Btn2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.table1.Add(this.Btn2);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.Btn2]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.Btn3 = new global::Gtk.Button();
		this.Btn3.Name = "Btn3";
		this.Btn3.UseUnderline = true;
		this.Btn3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.table1.Add(this.Btn3);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.Btn3]));
		w5.TopAttach = ((uint)(3));
		w5.BottomAttach = ((uint)(4));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.Btn4 = new global::Gtk.Button();
		this.Btn4.Name = "Btn4";
		this.Btn4.UseUnderline = true;
		this.Btn4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.table1.Add(this.Btn4);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.Btn4]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.Btn5 = new global::Gtk.Button();
		this.Btn5.Name = "Btn5";
		this.Btn5.UseUnderline = true;
		this.Btn5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.table1.Add(this.Btn5);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.Btn5]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.Btn6 = new global::Gtk.Button();
		this.Btn6.Name = "Btn6";
		this.Btn6.UseUnderline = true;
		this.Btn6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.table1.Add(this.Btn6);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.Btn6]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.Btn7 = new global::Gtk.Button();
		this.Btn7.Name = "Btn7";
		this.Btn7.UseUnderline = true;
		this.Btn7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.table1.Add(this.Btn7);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.Btn7]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.Btn8 = new global::Gtk.Button();
		this.Btn8.Name = "Btn8";
		this.Btn8.UseUnderline = true;
		this.Btn8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.table1.Add(this.Btn8);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.Btn8]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.Btn9 = new global::Gtk.Button();
		this.Btn9.Name = "Btn9";
		this.Btn9.UseUnderline = true;
		this.Btn9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.table1.Add(this.Btn9);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.Btn9]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.LeftAttach = ((uint)(2));
		w11.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.BtnClear = new global::Gtk.Button();
		this.BtnClear.Name = "BtnClear";
		this.BtnClear.UseUnderline = true;
		this.BtnClear.Label = global::Mono.Unix.Catalog.GetString("C");
		this.table1.Add(this.BtnClear);
		// Container child table1.Gtk.Table+TableChild
		this.BtnDecimalPt = new global::Gtk.Button();
		this.BtnDecimalPt.Name = "BtnDecimalPt";
		this.BtnDecimalPt.UseUnderline = true;
		this.BtnDecimalPt.Label = global::Mono.Unix.Catalog.GetString(".");
		this.table1.Add(this.BtnDecimalPt);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.BtnDecimalPt]));
		w13.TopAttach = ((uint)(4));
		w13.BottomAttach = ((uint)(5));
		w13.LeftAttach = ((uint)(2));
		w13.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.BtnDel = new global::Gtk.Button();
		this.BtnDel.Name = "BtnDel";
		this.BtnDel.UseUnderline = true;
		this.BtnDel.Label = global::Mono.Unix.Catalog.GetString("Del");
		this.table1.Add(this.BtnDel);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.BtnDel]));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.BtnDivide1 = new global::Gtk.Button();
		this.BtnDivide1.Name = "BtnDivide1";
		this.BtnDivide1.UseUnderline = true;
		this.BtnDivide1.Label = global::Mono.Unix.Catalog.GetString("/");
		this.table1.Add(this.BtnDivide1);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.BtnDivide1]));
		w15.LeftAttach = ((uint)(3));
		w15.RightAttach = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BtnEquals = new global::Gtk.Button();
		this.BtnEquals.Name = "BtnEquals";
		this.BtnEquals.UseUnderline = true;
		this.BtnEquals.Label = global::Mono.Unix.Catalog.GetString("=");
		this.table1.Add(this.BtnEquals);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.BtnEquals]));
		w16.TopAttach = ((uint)(4));
		w16.BottomAttach = ((uint)(5));
		w16.LeftAttach = ((uint)(3));
		w16.RightAttach = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BtnMinus = new global::Gtk.Button();
		this.BtnMinus.Name = "BtnMinus";
		this.BtnMinus.UseUnderline = true;
		this.BtnMinus.Label = global::Mono.Unix.Catalog.GetString("-");
		this.table1.Add(this.BtnMinus);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.BtnMinus]));
		w17.TopAttach = ((uint)(2));
		w17.BottomAttach = ((uint)(3));
		w17.LeftAttach = ((uint)(3));
		w17.RightAttach = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BtnMultiply = new global::Gtk.Button();
		this.BtnMultiply.Name = "BtnMultiply";
		this.BtnMultiply.UseUnderline = true;
		this.BtnMultiply.Label = global::Mono.Unix.Catalog.GetString("x");
		this.table1.Add(this.BtnMultiply);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.BtnMultiply]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(3));
		w18.RightAttach = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BtnPlus = new global::Gtk.Button();
		this.BtnPlus.Name = "BtnPlus";
		this.BtnPlus.UseUnderline = true;
		this.BtnPlus.Label = global::Mono.Unix.Catalog.GetString("+");
		this.table1.Add(this.BtnPlus);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.BtnPlus]));
		w19.TopAttach = ((uint)(3));
		w19.BottomAttach = ((uint)(4));
		w19.LeftAttach = ((uint)(3));
		w19.RightAttach = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BtnPlusMinus = new global::Gtk.Button();
		this.BtnPlusMinus.Name = "BtnPlusMinus";
		this.BtnPlusMinus.UseUnderline = true;
		this.BtnPlusMinus.Label = global::Mono.Unix.Catalog.GetString("+/-");
		this.table1.Add(this.BtnPlusMinus);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.BtnPlusMinus]));
		w20.TopAttach = ((uint)(4));
		w20.BottomAttach = ((uint)(5));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.BtnPwr = new global::Gtk.Button();
		this.BtnPwr.Name = "BtnPwr";
		this.BtnPwr.UseUnderline = true;
		this.BtnPwr.Label = global::Mono.Unix.Catalog.GetString("^");
		this.table1.Add(this.BtnPwr);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.BtnPwr]));
		w21.LeftAttach = ((uint)(2));
		w21.RightAttach = ((uint)(3));
		this.vbox3.Add(this.table1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.table1]));
		w22.Position = 1;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 406;
		this.DefaultHeight = 544;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
